/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'justi' at '9/25/16 10:15 PM' with Gradle 2.14.1
 *
 * @author justi, @date 9/25/16 10:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
